# Generated by Django 3.1.6 on 2022-03-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20220306_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('rank', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'inactive')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing')], max_length=50),
        ),
    ]
