# Generated by Django 3.1.6 on 2022-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20220412_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_prince',
            new_name='selling_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('On the way', 'On the way')], max_length=50),
        ),
    ]
