# Generated by Django 3.1.6 on 2022-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20220412_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed')], max_length=50),
        ),
    ]
