# Generated by Django 3.1.6 on 2022-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20220414_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')], max_length=50),
        ),
    ]
